#Experiment 8 - Tools for EDA
###Aditi Mishra
###ENTC A2
###25070123175


##1. Numpy Library

In [ ]:
#Declaration of Numpy

import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([[1,2,3],[4,5,6]])

print(a)
print(b)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Dimension of Numpy

print(a.ndim)
print(b.ndim)

1
2


In [ ]:
#Shape of Numpy

print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [ ]:
#Data type of Numpy

print(a.dtype)
print(b.dtype)

int64
int64


###In-built functions using Numpy

In [ ]:
#Zero matrix

np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Unity Matrix

np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [ ]:
c = a*2
d = a+5
print(c)
print(d)

[ 20  40  60  80 100]
[15 25 35 45 55]


In [ ]:
#Finding mean value

print(np.mean(a))
print(np.mean(b))

30.0
3.5


In [ ]:
#Finding median value

print(np.median(a))
print(np.median(b))

30.0
3.5


In [ ]:
#Finding max value

print(np.max(a))
print(np.max(b))

50
6


In [ ]:
#Finding minimum value

print(np.min(a))
print(np.min(b))

10
1


In [ ]:
print(np.sum(a))
print(np.sum(b))

150
21
